const shortVideos = [
  // CẬN HIỆN ĐẠI
  {
    id: 'vid1',
    src: '/videos/KCvideo1.mp4',
    category: 'Cận Hiện Đại',
    description: '"Ta về với mẹ ta thôi,làm con của mẹ như hồi còn thơ"',
    song: 'Nỗi Nhớ Hậu Phương – Ngô Đức Anh',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid2',
    src: '/videos/KCvideo2.mp4',
    category: 'Cận Hiện Đại',
    description: '"PROFILE CỰC KHỦNG CỦA \"TOP 1 SERVER\" - CỤ TRỊNH TỐ TÂM:\n\n✅ Họ và tên: Trịnh Tố Tâm\n✅ Năm sinh: 1945 (Ứng Hòa, Hà Đông cũ)\n✅ Nickname: Vua Mìn Đèo Hải Vân aka Con hùm xám đèo Hải Vân.\n✅ Thành tích: MVP đánh map đèo Hải Vân trong chiến tranh chống Mỹ cứu nước.\n✅ Sở trường: Đặt mìn.\n\n🎖 Thành tích:\n\n🔸 Chỉ huy 58 trận chiến.\n🔸 Tiêu diệt 1.500 lính địch\n🔸 Phá hủy 61 xe quân sự\n🔸 Đánh bật 19 đoàn tàu hỏa\n\n🏆 Danh hiệu\n\n▪️ Được phong Anh Hùng Lực Lượng Vũ Trang Nhân Dân khi mới 26 tuổi.\n▪️ 1 Huân chương Độc lập hạng Ba\n▪️ 1 Huân chương Kháng chiến chống Mỹ cứu nước hạng Nhất\n▪️ 13 Huân chương chiến công hạng Nhất, Nhì, Ba\n▪️ 3 Huân chương giải phóng hạng Nhất\n▪️ 53 lần được phong tặng danh hiệu Dũng sỹ diệt Mỹ.\n\nCụ Trịnh Tố Tâm là người có nhiều huân, huy chương nhất trong Quân đội nhân dân Việt Nam.\n\nGiặc rất nhiều lần treo thưởng hậu hĩnh cho ai bắt hoặc tiêu diệt được \"Hùm xám đèo Hải Vân\" nhưng như các bạn thấy đấy, danh hiệu \"Dũng sĩ diệt Mỹ\" là dành cho những chiến sĩ diệt từ 5 quân địch trở lên, riêng cụ có 53 lần được phong tặng.\n\nViệt Nam chúng ta không có những phim về siêu anh hùng nhưng thực tế trải suốt chiều dài lịch sử, chúng ta đã có rất nhiều siêu anh hùng như thế đấy!!!!"',
    song: 'Gửi Người Chiến Sĩ – Trọng Tấn',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid3',
    src: '/videos/KCvideo3.mp4',
    category: 'Cận Hiện Đại',
    description: '"\"Con ơi, hãy tha lỗi cho mẹ...\" – lời thì thầm nghẹn ngào của bà mẹ Lê Thị Nghệ khi ôm lấy chiếc khăn năm xưa của người con trai đã hy sinh, là một hình ảnh lay động lòng người suốt nhiều thế hệ.\n\nBà Lê Thị Nghệ, quê ở Quảng Trị – vùng đất bom đạn gió lửa trong suốt những năm tháng chiến tranh – là một người mẹ Việt Nam anh hùng, đã tiễn đưa con trai mình ra chiến trường mà không một lần oán thán. Ngày con ngã xuống nơi tuyến lửa, bà chỉ lặng lẽ giữ lại chiếc khăn tay – kỷ vật duy nhất còn sót lại – như một phần linh hồn con vẫn còn hiện diện. Bao năm trôi qua, chiếc khăn ấy đã ngả màu, nhưng tình mẹ thì chưa từng phai nhạt.\n\nBà đã cống hiến cả tuổi xuân, cả tình yêu thương, và cả máu thịt để đổi lấy độc lập cho đất nước. Người phụ nữ gầy gò, tóc bạc trắng ấy từng ngày vẫn đến nghĩa trang liệt sĩ, tay run run lau tấm bia có khắc tên con, miệng khe khẽ kể chuyện đời, như thể con vẫn đang ở bên mình.\n\nChiến tranh đã lùi xa, nhưng ký ức và nỗi đau của những bà mẹ như bà Nghệ chưa bao giờ phai nhòa. Họ là nhân chứng sống cho sự hy sinh thầm lặng, là biểu tượng của lòng yêu nước, của đức hy sinh cao cả, và của tình mẫu tử thiêng liêng vượt qua cả ranh giới sinh – tử.\n\nKhông có tượng đài nào đủ lớn để tạc nên công lao của bà. Không có bài hát nào đủ lời để kể hết nỗi lòng người mẹ. Nhưng hình ảnh bà ôm chiếc khăn – ôm cả một trời yêu thương và mất mát – sẽ mãi mãi là biểu tượng bất diệt trong lòng mỗi người dân Việt Nam."',
    song: 'Không rõ tên bài hát',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid4',
    src: '/videos/KCvideo4.mp4',
    category: 'Cận Hiện Đại',
    description: '"Những cậu sinh viên trẻ năm xưa, với ánh mắt rực lửa và lý tưởng sục sôi, đã rời giảng đường để khoác lên mình màu áo lính, bước vào chiến trường khốc liệt. Họ đã sống, chiến đấu, và hy sinh tuổi trẻ cho độc lập của dân tộc. Giữa khói bom và tiếng đạn, họ vẫn giữ trong tim hình ảnh ngôi trường, tiếng giảng bài, và lời hứa hẹn sẽ có ngày trở về.\n\nVà ngày ấy đã đến – không kèn, không trống, chỉ có những bước chân rụt rè trở lại mái trường xưa, nơi từng chứng kiến họ chia tay trong nước mắt. Giờ đây, họ đã là những người đàn ông trưởng thành, mang trên mình dấu vết của chiến tranh nhưng ánh mắt vẫn vẹn nguyên niềm tin tuổi trẻ. Thầy cô, bạn bè, và cả những dãy bàn ghế cũ kỹ như cùng lặng đi trong phút giây đoàn tụ.\n\nCó những người trở về trong vòng tay bạn bè, có những người chỉ còn tấm ảnh thờ lặng lẽ trên bàn tưởng niệm. Những giọt nước mắt rơi – không chỉ vì mất mát – mà vì lòng biết ơn, vì họ đã giữ trọn lời hứa: trở về, dù muộn, dù không còn nguyên vẹn.\n\nCâu chuyện ấy không chỉ là một ký ức, mà là minh chứng cho lòng yêu nước của một thế hệ – những sinh viên đã đổi bút mực lấy súng đạn, và viết nên trang sử bằng chính tuổi xuân của mình."',
    song: 'Không rõ tên bài hát',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid5',
    src: '/videos/KCvideo5.mp4',
    category: 'Cận Hiện Đại',
    description: ' "“Mẹ ơi, con vẫn chưa làm được gì nhiều cho mẹ…” – đó là dòng mở đầu trong bức thư cuối cùng của người lính trẻ gửi về từ mặt trận khốc liệt, khi thời khắc sinh tử đã cận kề. Trong tiếng bom rơi đạn nổ, cậu vẫn gắng gượng viết vài dòng cho người mẹ già nơi quê nhà – người đã tiễn con đi trong nước mắt và hy vọng.\n\nBức thư ấy không dài, nhưng chất chứa tất cả tình cảm, nỗi nhớ, và khát vọng dang dở của một người con chưa kịp trưởng thành. Cậu kể về những đêm nằm trong chiến hào lạnh giá, nhớ bát cơm mẹ nấu, nhớ giọng nói dịu dàng ru ngủ. Cậu xin lỗi vì không thể ở bên chăm sóc mẹ khi trái gió trở trời, xin lỗi vì những lần nghịch dại chưa kịp nói lời yêu thương.\n\nMỗi con chữ đều như thấm đẫm nước mắt – nước mắt của một người con sắp phải rời xa thế giới này mãi mãi. Nhưng hơn tất cả, cậu nhắn nhủ: “Mẹ ơi, nếu con có hy sinh, mẹ đừng buồn. Con ra đi, nhưng con tin đất nước mình sẽ độc lập, và những đứa trẻ sau này sẽ được sống trong hòa bình.”\n\nĐoạn thư ấy – trích trong phim *Mùi Cỏ Cháy* – không chỉ là một chi tiết điện ảnh, mà còn là tiếng lòng của biết bao người lính trẻ năm xưa. Nó khiến chúng ta lặng người, để rồi nhận ra rằng: phía sau mỗi chiến sĩ ra trận, là một người mẹ chờ con, một mái nhà không bao giờ tắt lửa hy vọng."',
    song: 'Không rõ tên bài hát',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid6',
    src: '/videos/KCvideo6.mp4',
    category: 'Cận Hiện Đại',
    description: '"\"Mẹ ơi, trong ngày khải hoàn, sẽ không có con của mẹ đâu...\" – câu nói nghẹn ngào từ trang nhật ký của nữ bác sĩ Đặng Thùy Trâm đã làm lay động hàng triệu trái tim. Trong phim *Đừng Đốt*, câu nói ấy không chỉ là lời tạm biệt, mà là tiếng lòng của cả một thế hệ thanh niên đã sống, chiến đấu và ngã xuống vì Tổ quốc.\n\nKhi mới 27 tuổi, Đặng Thùy Trâm đã rời bỏ phòng khám, mái nhà, và vòng tay cha mẹ để đến với chiến trường ác liệt miền Trung. Giữa mưa bom, bão đạn, chị vẫn kiên cường làm nhiệm vụ cứu chữa thương binh, viết nhật ký mỗi đêm bằng tình yêu tha thiết dành cho cuộc sống, cho quê hương, và cho mẹ.\n\nTrong những dòng cuối cùng, chị viết cho mẹ bằng tất cả bình thản và can đảm: không oán than, không sợ hãi, chỉ có tình yêu và lời xin lỗi. Vì chị biết, ngày đất nước hoà bình, chị sẽ không thể có mặt. Nhưng sự hy sinh ấy không vô nghĩa. Chị đã sống một cuộc đời rực cháy, sống đẹp đến giây phút cuối cùng.\n\nBức thư ấy, trang nhật ký ấy – và cả bộ phim *Đừng Đốt* – là minh chứng sống cho tinh thần bất khuất, cho lý tưởng cao đẹp và trái tim chan chứa nhân ái của một người con gái Việt Nam. Nó nhắc chúng ta rằng: hòa bình hôm nay được đánh đổi bằng máu, bằng nước mắt, và bằng tình yêu lớn lao của những người không trở về."',
    song: 'Mẹ Yêu Con ',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },

  // PHONG KIẾN
  {
    id: 'vid7',
    src: '/videos/PKvideo1.mp4',
    category: 'Phong Kiến',
    description: '"Dưới triều Lê Thánh Tông – một trong những thời kỳ hưng thịnh nhất của Đại Việt – quốc gia không chỉ phát triển rực rỡ về kinh tế, giáo dục và luật pháp, mà còn hình thành một tư tưởng độc lập, đầy kiêu hãnh về chính trị và văn hóa. Trong bối cảnh Trung Hoa luôn tự nhận là "thiên triều" – trung tâm của thiên hạ – thì Đại Việt cũng không chịu lép vế.\n\nVua Lê Thánh Tông đã tổ chức triều chính cực kỳ quy củ, ban hành Bộ luật Hồng Đức tiến bộ, xây dựng mạng lưới trường học khắp cả nước và trọng dụng nhân tài qua khoa cử. Không chỉ vậy, nhà vua còn chủ động mở rộng lãnh thổ về phương Nam, khẳng định uy quyền Đại Việt trên bản đồ khu vực.\n\nTrong các bản sắc phong, sắc dụ, ngôn từ của triều đình Lê Thánh Tông cũng thể hiện tư thế của một quốc gia "thiên triều phương Nam", tự xem mình là trung tâm văn hóa, đạo lý của một vùng. Điều đó cho thấy, Đại Việt thời kỳ này không còn mang tâm lý thần phục, mà đã tự tin sánh vai với các quốc gia lớn trong khu vực.\n\nTư tưởng ấy không chỉ là biểu hiện của lòng tự tôn dân tộc, mà còn là minh chứng cho một nền văn minh Đại Việt đã đạt đến độ chín, có thể đối thoại ngang hàng với bất kỳ đế chế nào trong khu vực Đông Á."',
    song: 'Trăng Về Làng – Quang Linh',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid8',
    src: '/videos/PKvideo2.mp4',
    category: 'Phong Kiến',
    description: ' "🏹 PROFILE HÙNG VĨ CỦA HƯNG ĐẠO ĐẠI VƯƠNG – TRẦN QUỐC TUẤN:\n\n✅ Họ tên: Trần Quốc Tuấn (陳國峻)\n✅ Tước vị: Hưng Đạo Đại Vương – Quốc công tiết chế tối cao triều Trần\n✅ Năm sinh – mất: 1228 – 1300\n✅ Quê quán: Tức Mặc, phủ Thiên Trường (nay thuộc Nam Định)\n\n⚔️ Chiến công hiển hách:\n\n🔸 Tổng chỉ huy 3 lần đánh bại quân Nguyên Mông hùng mạnh (1258, 1285, 1288)\n🔸 Tác giả Binh thư yếu lược – tinh hoa quân sự Đại Việt\n🔸 Lập mưu trận Bạch Đằng năm 1288 tiêu diệt đại quân Thoát Hoan – trận thủy chiến vĩ đại nhất lịch sử dân tộc\n🔸 Được các sử gia phong là “thiên tài quân sự kiệt xuất nhất trong lịch sử Việt Nam”\n\n🏆 Phẩm chất & di sản:\n\n▪️ Đạo đức mẫu mực, nhân cách cao quý, trung nghĩa – từng dẹp bỏ thù riêng vì nghĩa lớn nước nhà\n▪️ Được nhân dân tôn thờ như Thánh nhân: Đức Thánh Trần\n▪️ Hình tượng bất tử trong văn hóa dân gian, từ đền Trần, hội đền Kiếp Bạc đến trong lòng hàng triệu người Việt\n▪️ Tư tưởng về quốc phòng, đoàn kết toàn dân vẫn còn nguyên giá trị đến ngày nay\n\n🕊 Danh ngôn bất hủ:\n“...Nếu bệ hạ muốn hàng, hãy chém đầu tôi trước đã!” – Trần Quốc Tuấn nói với vua Trần khi nhà Nguyên đem thư dụ hàng.\n\n📜 Di chúc để lại:\n“Phàm làm tướng phải khoan hoà nhân hậu, biết dùng mưu kế, giữ phép nước nghiêm minh, như vậy mới mong giữ vững giang sơn xã tắc.”\n\nTrần Hưng Đạo không chỉ là một vị tướng – ông là linh hồn của cả một dân tộc trong thời khắc hiểm nghèo. Một tượng đài của ý chí Việt Nam, một biểu tượng bất diệt cho tinh thần đánh bại mọi xâm lược, dù là đội quân hùng mạnh nhất thế giới."',
    song: 'Không rõ bài hát',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid9',
    src: '/videos/PKvideo3.mp4',
    category: 'Phong Kiến',
    description: '"⚔️ HỒ SƠ HUYỀN THOẠI CỦA NGUYỄN HUỆ – QUANG TRUNG HOÀNG ĐẾ:\n\n✅ Họ tên thật: Nguyễn Huệ (阮惠)\n✅ Tước hiệu: Quang Trung Hoàng Đế (光中皇帝)\n✅ Triều đại: Tây Sơn (1778–1802)\n✅ Năm sinh – mất: 1753 – 1792\n✅ Quê quán: Phú Xuân (nay thuộc Bình Định)\n\n🔥 Vị vua – danh tướng kiệt xuất:\n\n🔸 Một trong ba anh em nhà Tây Sơn lãnh đạo khởi nghĩa nông dân lớn nhất lịch sử Việt Nam\n🔸 Thống lĩnh chiến dịch đại phá quân Xiêm tại trận Rạch Gầm – Xoài Mút (1785) – một trong những chiến thắng kinh điển nhất trên sông nước\n🔸 Năm 1789, đánh tan 29 vạn quân Thanh trong vòng **7 ngày Tết** tại trận Ngọc Hồi – Đống Đa, ghi danh là một trong những chiến thắng thần tốc nhất thế giới\n🔸 Xưng đế năm 1788, lập nên triều đại Tây Sơn chính danh, mở đầu cải cách quốc gia toàn diện từ giáo dục, binh bị đến bang giao\n\n🏆 Tư tưởng và di sản:\n\n▪️ Dẫn đầu cải cách chữ Nôm và giáo dục quốc ngữ thời kỳ đầu\n▪️ Đề cao khoa học, trọng dụng nhân tài, xóa bỏ tầng lớp quý tộc lạc hậu\n▪️ Mưu lược quân sự bậc thầy, từng dự định đem quân tiến đánh phương Bắc nếu sống lâu hơn\n▪️ Tinh thần độc lập, tự cường, dân tộc trong từng chính sách trị quốc\n\n🕊 Danh ngôn truyền kỳ:\n“Đánh cho sử tri Nam quốc anh hùng chi hữu chủ” – một câu nói bất hủ trước trận Đống Đa, thể hiện rõ chí khí vua tôi Tây Sơn\n\n⚜️ Di sản:\nNguyễn Huệ – Quang Trung không chỉ là một thiên tài quân sự, ông còn là biểu tượng sống động của lòng yêu nước, ý chí dân tộc và sức mạnh đoàn kết nhân dân. Dù triều đại Tây Sơn tồn tại không dài, nhưng ánh hào quang từ chiến thắng và những cải cách của ông đã khắc sâu vào lịch sử Việt Nam như một kỷ nguyên rực rỡ nhất.\n\nNgười anh hùng áo vải đất Tây Sơn – vẫn mãi là niềm tự hào muôn đời của dân tộc!"',
    song: 'Không rõ bài hát',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid10',
    src: '/videos/PKvideo4.mp4',
    category: 'Phong Kiến',
    description: ' "Không phải ai cầm gươm đứng lên cũng được gọi là anh hùng. Có người tên tuổi vang danh sử sách, có người lặng lẽ nằm lại nơi rừng sâu núi thẳm, chẳng một hàng bia mộ. Nhưng dù được nhắc đến hay không, dù được phong tước hay chưa từng ghi tên, mỗi người đã ngã xuống vì Tổ quốc – đều là nghĩa sĩ.\n\nHọ là những chàng trai tuổi mười tám đôi mươi, những cô gái chưa kịp tròn tuổi xuân. Họ rời mái nhà, bỏ lại cha mẹ, người thương và giấc mơ dang dở, để dấn thân vào lửa đạn. Có người cầm súng, có người gùi gạo, có người đưa thư, có người chỉ để ngã xuống làm tấm khiên sống cho đồng đội vượt qua.\n\nKhông ai đếm được hết bao nhiêu nghĩa sĩ đã không trở về. Tên họ không có trong sách giáo khoa, mặt họ không có trên tượng đài, nhưng máu của họ đã nhuộm đỏ từng tấc đất quê hương, hòa vào dòng chảy bất tận của lịch sử.\n\nChúng ta gọi họ là "nghĩa sĩ" – không vì chức danh, không vì cấp bậc – mà vì họ đã chọn đứng về phía chính nghĩa, về phía nhân dân, và nằm xuống trong tư thế ngẩng cao đầu. Lịch sử Việt Nam rực rỡ không chỉ bởi những chiến thắng, mà còn bởi hàng vạn nghĩa sĩ vô danh đã ngã xuống trong thầm lặng.\n\nVà trong mỗi nén nhang, mỗi lời tri ân hôm nay, xin hãy nhớ đến họ – những người không cần được gọi là anh hùng, nhưng mãi mãi là linh hồn của dân tộc."',
    song: 'Remix',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid11',
    src: '/videos/PKvideo5.mp4',
    category: 'Phong Kiến',
    description: '"Nguyễn Trãi – người được hậu thế tôn vinh là "anh hùng dân tộc", "danh nhân văn hóa thế giới", là bậc đại trí, đại trung, đại nhân hiếm có trong lịch sử Việt Nam. Sinh năm 1380 trong một gia đình khoa bảng, ông sớm thể hiện tài năng xuất chúng về văn chương, tư tưởng và chính trị.\n\nSau khi nhà Hồ thất thủ, Nguyễn Trãi rút về ở ẩn, nhưng khi Lê Lợi dựng cờ khởi nghĩa chống giặc Minh, ông đã dốc lòng phò tá. Với trí tuệ siêu việt và lòng yêu nước nồng nàn, ông trở thành kiến trúc sư chiến lược của cuộc kháng chiến Lam Sơn. Những áng "Quân trung từ mệnh tập" và "Bình Ngô đại cáo" do ông chấp bút không chỉ là đỉnh cao của văn chính luận, mà còn là bản tuyên ngôn độc lập đanh thép đầu tiên của dân tộc Việt.\n\nNguyễn Trãi không chỉ là một nhà mưu lược đại tài, mà còn là một nhà thơ nhân ái, một học giả lớn với tư tưởng vì dân. Ông luôn trăn trở về sinh kế của người nghèo, mưu cầu cho dân an, nước trị. Trong thơ văn của ông, hiện lên hình ảnh quê hương thanh bình, lòng thương dân sâu sắc và khát vọng về một xã hội lý tưởng.\n\nThế nhưng, cuộc đời ông kết thúc trong bi kịch Lệ Chi Viên – bị vu oan và chu di tam tộc khi tuổi đã ngoài 60. Phải đến hơn 20 năm sau, ông mới được minh oan, và ngày nay, tên tuổi Nguyễn Trãi sống mãi trong lòng dân tộc như một biểu tượng của trí tuệ, chính nghĩa và lòng yêu nước bền bỉ.\n\nNguyễn Trãi – người đã viết nên bản anh hùng ca không chỉ bằng ngôn từ, mà bằng cả cuộc đời dấn thân, phụng sự nhân dân và Tổ quốc."',
    song: 'Chầu Văn Thăng Long – NSƯT Thanh Hoài',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid12',
    src: '/videos/PKvideo6.mp4',
    category: 'Phong Kiến',
    description: '"Giữa những năm tháng biên cương Đại Việt liên tục bị quấy nhiễu, nhà Tống nuôi mộng xâm lược phương Nam, triều đình Lý đứng trước lựa chọn sống còn: nên giữ thế phòng thủ hay chủ động tấn công. Trong chính điện rực lửa khí thiêng, vua Lý Nhân Tông và đại tướng Lý Thường Kiệt đã có một cuộc đối đáp ghi dấu vào lịch sử.\n\nVua hỏi: \"Giặc ngày một lấn tới, khanh cho rằng nên giữ vững biên thùy, hay đem quân vượt biên trước?\". Lý Thường Kiệt đáp lời không chút do dự: \"Thần không sợ chiến bại, chỉ sợ mất nước. Ngồi chờ giặc đến là điều ngu dốt. Chúng ta phải đánh trước để phá thế giặc, khiến chúng không kịp trở tay. Đó là đạo làm tướng.\"\n\nChính nhờ tinh thần quyết đoán và mưu lược ấy, Lý Thường Kiệt đã chỉ huy chiến dịch đánh thẳng vào Khâm Châu, Ung Châu – phá tan căn cứ hậu cần của quân Tống, mở ra thế chủ động tuyệt đối cho Đại Việt trong cuộc chiến vệ quốc vĩ đại. Sau đó, ông dựng phòng tuyến Như Nguyệt và làm nên chiến công chấn động lịch sử.\n\nĐó không chỉ là chiến thắng về quân sự, mà còn là biểu tượng cho bản lĩnh của một dân tộc không chờ bị xâm lược mới đứng dậy – mà sẵn sàng ra đòn phủ đầu để giữ vững giang sơn.\n\nCuộc đối đáp giữa hai bậc minh quân – đại tướng ấy chính là sự giao thoa giữa lý trí và dũng khí, giữa trí tuệ và lòng yêu nước – tinh thần ấy vẫn còn nguyên giá trị trong mọi thời đại."',
    song: 'Không rõ bài hát',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid13',
    src: '/videos/PKvideo7.mp4',
    category: 'Phong Kiến',
    description: ' "Năm 1075, khi nhà Tống ráo riết chuẩn bị xâm lược Đại Việt, đại tướng Lý Thường Kiệt – bằng tầm nhìn chiến lược và khí phách của một bậc thiên tài quân sự – đã chủ động phát động chiến dịch đánh thẳng vào đất Tống, mở đầu bằng trận đánh **Ung Châu** vang danh thiên cổ.\n\nKhông chờ giặc kéo đến, Lý Thường Kiệt tập hợp một đạo quân tinh nhuệ, vượt sông, băng rừng, bí mật tiến công các châu Khâm, Liêm, và đặc biệt là **Ung Châu – căn cứ trọng yếu của quân Tống ở biên giới phương Nam**. Sau gần 40 ngày vây hãm, với hỏa công, vũ lực và cả chiến thuật tâm lý, quân Đại Việt đã phá tan thành trì, tiêu diệt hơn 8.000 binh sĩ địch, thu lấy vũ khí, lương thảo và làm rúng động triều đình phương Bắc.\n\nĐây không chỉ là một chiến thắng quân sự, mà còn là một đòn phủ đầu táo bạo – thể hiện tư tưởng **“tiên phát chế nhân”**: ra tay trước để phá vỡ thế trận của địch, khiến chúng không thể phản công có tổ chức.\n\nChiến dịch Ung Châu trở thành một mốc son trong lịch sử chống ngoại xâm của dân tộc, khẳng định bản lĩnh và tư duy vượt thời đại của quân đội Đại Việt. Và Lý Thường Kiệt – với tầm vóc của một vị danh tướng vĩ đại – đã được khắc tên vào lịch sử như một người hùng biết chớp thời cơ, dám hành động và dám chiến thắng."',
    song: 'Không rõ bài hát',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },

  // AI
  {
    id: 'vid14',
    src: '/videos/AIvideo1.mp4',
    category: 'AI',
    description: ' "Bạn tỉnh dậy trong một căn lán lợp lá cọ, tiếng kèn đồng vọng lên từ chân núi, và người bên cạnh thì thào: \"Dậy đi, trinh sát viên, chúng ta phải vượt rừng trước khi mặt trời mọc.\" Vẫn chưa hiểu chuyện gì xảy ra, bạn nhìn quanh: không có điện thoại, không có GPS – chỉ có một thanh đoản đao, một bộ áo vải bạc màu và chiếc bản đồ vẽ tay bằng mực tàu. Chào mừng bạn đến với **một ngày làm quân trinh sát triều Trần** – giữa thời kỳ sục sôi chuẩn bị kháng chiến chống Nguyên Mông.\n\nNhiệm vụ: len lỏi qua những cánh rừng Lạng Sơn, thám sát lộ trình tiến quân của giặc, bí mật ghi lại thông tin, và trở về trước khi trời tối. Một sai lầm nhỏ thôi cũng có thể khiến bạn bị phục kích hoặc không bao giờ quay lại. Không có máy bay trinh sát, không có vệ tinh – tất cả phụ thuộc vào đôi mắt, đôi tai và trí nhớ của bạn.\n\nBạn gặp những toán quân dã chiến, những dân binh địa phương sẵn sàng hy sinh để giữ kín thông tin. Bạn nghe chuyện về Thoát Hoan, về binh lực khổng lồ đang rục rịch phía Bắc, và trái tim bạn bắt đầu sục sôi – không chỉ vì sợ hãi, mà vì ý chí sống còn của một dân tộc.\n\nTrong một ngày ấy, bạn không còn là người hiện đại. Bạn là **mắt tai của quân đội nhà Trần**, là người sống giữa ranh giới của cái chết và chiến thắng. Bạn hiểu vì sao cha ông ta gọi giặc là "thiên binh vạn mã", và vì sao quyết không để giặc đặt chân đến Thăng Long thêm một lần nữa.\n\nKhi bạn trở lại lán an toàn, trời vừa kịp tối, bạn thở phào, và chỉ khi đó bạn mới nhận ra: một ngày làm quân trinh sát triều Trần, là cả một đời sống trong khí phách của một dân tộc chưa bao giờ cúi đầu."',
    song: 'AI Voice – Synthesized',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid15',
    src: '/videos/AIvideo2.mp4',
    category: 'AI',
    description: ' "Tiếng trống trận vang dội, nước sông Bạch Đằng cuồn cuộn vỗ vào mạn thuyền. Bạn mở mắt, tay cầm mái chèo, chân dẫm trên sàn gỗ đầy dây neo và mồi dầu. Không còn bàn phím, không còn điện thoại – bạn vừa xuyên không trở thành **một thủy binh thời Trần**, ngay trước trận đánh lớn với đạo quân Nguyên Mông lẫy lừng.\n\nÁnh bình minh chưa kịp rạng, khói sương đã phủ mờ khắp cửa biển. Bạn đứng giữa hạm đội đang mai phục, quanh bạn là hàng trăm chiến thuyền ẩn mình sau những cọc gỗ lim vót nhọn – thứ vũ khí bí mật sắp sửa viết nên chiến thắng vang dội trong sử Việt.\n\nLệnh phát ra: "Giữ vững đội hình! Khi thủy triều lên, dụ chúng tiến sâu!". Tim bạn đập thình thịch, vừa háo hức, vừa kinh hãi. Phía xa là những con thuyền lớn của giặc, chiến kỹ dồn dập, cung tên sẵn sàng. Nhưng thủy binh Đại Việt không hoảng loạn. Bạn hiểu rằng mình là một phần của chiến thuật thiên tài – nơi thiên thời, địa lợi và nhân tâm hòa làm một.\n\nBạn cùng đồng đội dốc sức chèo lái, lùa quân giặc vào bãi cọc đã được bố trí từ trước. Khi nước rút, hàng ngàn cọc gỗ nhọn hoắt trồi lên khỏi mặt nước như nanh sói, xuyên thủng bụng tàu của giặc. Tiếng reo hò dậy sóng, khói lửa bốc lên giữa dòng Bạch Đằng. Đó không chỉ là chiến thắng, mà là **một bản tuyên ngôn bằng máu, nước và ý chí bất khuất của Đại Việt**.\n\nKhi bạn trở lại thực tại, tim vẫn còn đập dồn dập. Một ngày làm thủy binh nhà Trần không chỉ là cuộc chiến trên sông – mà là hành trình xuyên qua lòng kiêu hãnh dân tộc. Và bạn sẽ không bao giờ nhìn sông nước Việt Nam bằng ánh mắt cũ nữa."',
    song: 'Cảm Hứng Công Nghệ – Instrumental',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid16',
    src: '/videos/AIvideo3.mp4',
    category: 'AI',
    description: ' "Bạn choàng tỉnh giữa làn hương trầm phảng phất, quanh mình là những bức rèm lụa mỏng manh, nền đá lát gạch hoa sen mát lạnh dưới chân. Không có điện thoại, không tiếng chuông báo thức – chỉ có tiếng chuông đồng ngân nga từ tháp Báo Thiên xa xa. Bạn vừa thức dậy… và trở thành **một tỳ nữ trong hậu cung triều Lý**.\n\nChiếc yếm đào mỏng nhẹ được xếp gọn trên chiếc tráp sơn son, áo tứ thân đính chỉ vàng là thứ phục trang bạn phải mặc mỗi sáng sớm trước giờ dâng trà cho công chúa. Bạn không có tên, chỉ có chức phận – là một trong hàng trăm người hầu sống trong cung đình nơi quyền lực và lễ nghi bủa vây như những sợi chỉ tơ giăng mắc.\n\nBạn học cách cúi đầu thật thấp, đi nhẹ, nói khẽ, hiểu từng ánh mắt của hoàng hậu, biết khi nào nên lùi, lúc nào cần im. Nhưng giữa chốn cung cấm ngỡ toàn yên bình ấy, bạn nghe được tin đồn về những biến động ngoài kinh thành – việc vua Lý Nhân Tông đang bàn luận cùng đại thần Lý Thường Kiệt, hay việc chùa Quốc Tử Giám sắp tuyển chọn tỳ nữ biết chữ để dạy cho công nương học nữ công, thi thư.\n\nTrong tim bạn dấy lên một điều lạ lùng: phải chăng mình không chỉ là một tỳ nữ vô danh? Phải chăng giữa triều đại rực rỡ ấy, một người con gái nhỏ bé vẫn có thể góp phần vào câu chuyện lớn lao của đất nước?\n\nMột ngày làm tỳ nữ thời Lý là như vậy – đầy lễ nghi, áp lực, nhưng cũng mở ra những góc nhìn hiếm hoi về cuộc sống hậu cung, về số phận người phụ nữ xưa. Bạn không chỉ xuyên không vào lịch sử – mà còn sống trong từng hơi thở của quá khứ, nơi mà từng lời nói, cử chỉ nhỏ cũng là một phần của dòng chảy ngàn năm văn hiến."',
    song: 'Bắc Bling - Hòa Minzy',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid17',
    src: '/videos/AIvideo4.mp4',
    category: 'AI',
    description: '"Nước sông lạnh ngắt, bùn đất quánh dày, tay bạn tứa máu vì xiết chặt sợi thừng kéo cọc. Tiếng sấm vọng lại từ xa chẳng phải trời nổi giông – mà là tiếng giặc chuẩn bị kéo quân. Nhưng bạn không nhìn thấy kẻ thù. Thứ trước mắt bạn… là một chiếc cọc lim to bằng bắp đùi người, được vót nhọn như một mũi thương khổng lồ. Và nhiệm vụ của bạn: **ép nó xuống lòng sông Bạch Đằng.**\n\nBạn không phải tướng quân. Bạn không cần biết khi nào thủy triều lên hay rút. Bạn chỉ biết: khi hàng ngàn chiếc cọc này đứng vững dưới đáy sông, chúng sẽ biến cả dòng chảy thành một cái bẫy tử thần cho thuyền giặc. Mỗi cú đóng cọc là một lời thề. Mỗi tiếng gỗ rẽ bùn sâu là một bản tuyên ngôn thầm lặng cho độc lập.\n\nXung quanh bạn là những người nông dân bỏ ruộng, những trai tráng từ làng chài ven biển – ai cũng câm lặng mà làm. Mồ hôi hòa với bùn, máu thấm vào nước – không một ai than vãn. Bạn biết rằng **mình chỉ là một người vô danh**, nhưng bạn tin: chiến thắng chỉ đến khi có đủ những bàn tay vô danh như thế.\n\nSau này, sử sách nhắc nhiều đến Trần Hưng Đạo, đến mưu lược trận địa. Nhưng không mấy ai nhớ tên người lính ép cọc. **Người như bạn.** Và bạn chấp nhận điều đó, như cách bạn gục xuống bên bãi cọc cuối cùng – giữa nước triều rút – mỉm cười vì biết: lịch sử đã được đóng xuống lòng sông… bằng chính đôi tay này."',
    song: 'Translate Voices – AI Tools',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid18',
    src: '/videos/AIvideo5.mp4',
    category: 'AI',
    description: ' "Bạn không cầm gươm, cũng chẳng bắn tên. Tay bạn chỉ có đôi quang gánh, vai trĩu nặng từng bao thóc, từng hũ muối, từng túi khô cá. Nhưng mỗi bước chân bạn đi, là một nhịp thở được giữ lại cho những người đang ở tuyến đầu. Bạn là lính vận lương. Một cái bóng lặng lẽ giữa đại quân rợp trời cờ xí.\n\nĐường vận chuyển không trải nhựa – mà là núi cao, khe sâu, bùn đất lầy lội. Có những đêm bạn vượt rừng, gió hú lạnh buốt, chân run vì đói. Có khi giặc rình rập ngay lối mòn, chỉ cần sơ suất là mất cả đoàn lương. Nhưng không ai than thở. Vì phía trước, đại quân đang chờ. **Không có lương, không có trận đánh. Không có bạn, không có chiến thắng.**\n\nBạn nhớ lần đầu được giao nhiệm vụ, người chỉ huy vỗ vai bảo: \"Đánh giặc là việc của tướng, nuôi quân là việc của dân. Nhưng một khi đã khoác áo trận, thì ai cũng là chiến sĩ.\" Câu nói ấy đi theo bạn qua bao con dốc, bao lần trượt chân, bao vết chai máu đỏ trên vai.\n\nKhi thóc đến nơi, bạn lùi lại. Không ai biết tên bạn. Không có chiến công. Nhưng bạn biết: từng nắm cơm họ ăn, từng giọt nước họ uống – là từ đôi vai của những người như bạn. Người ta ghi danh tướng soái. **Lịch sử âm thầm khắc tên bạn vào đá núi, vào đất đai – nơi những đoàn vận lương đi qua.**\n\nBạn là người lính vận chuyển lương thảo. Không cần chiến công, chỉ cần đất nước thắng trận. Thế là đủ."',
    song: 'Thơ Ca Dữ Liệu – AI Composition',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: 'vid19',
    src: '/videos/AIvideo6.mp4',
    category: 'AI',
    description: ' "Bạn choàng tỉnh giữa tiếng vó ngựa dồn dập, tay nắm chặt cán kiếm còn đẫm mồ hôi. Người hầu quỳ trước mặt, run giọng: "Thưa bệ hạ, quân Thanh đã vượt biên giới, Thăng Long thất thủ". Bạn ngỡ là một giấc mơ, nhưng rồi nhìn quanh: long bào vắt bên án thư, bản đồ trải rộng, chiếu chỉ còn chưa kịp đóng dấu. **Bạn… chính là Hoàng đế Quang Trung.**\n\nChỉ còn đúng 6 ngày để tập kết quân, vượt sông Hồng, và đánh tan 29 vạn quân Thanh đang hoành hành ngoài bắc. Mỗi giờ trôi qua là sinh mạng hàng ngàn người. Bạn – người xuyên không – giờ gánh cả vận mệnh đất nước trên vai.\n\nBạn triệu tập đại thần, lệnh khẩn cấp từ Phú Xuân ra Bắc. Trên lưng ngựa, bạn cảm nhận gió Tết lạnh buốt phả vào mặt. Quân sĩ đồng lòng, tiếng hô vang vọng: “Sống chết theo vua!” – và bạn hiểu: **đây không còn là một giấc mơ – mà là cơ hội viết nên lịch sử bằng chính tay mình.**\n\nTừng bước hành quân, từng mưu lược, từng trận đánh thần tốc Ngọc Hồi – Đống Đa như một bản giao hưởng chiến trận. Khi chiến thắng đến, cờ đỏ sao vàng chưa có, nhưng **ý chí Việt Nam đã tung bay ngút trời**.\n\nBạn đứng trên chiến trường, giữa xác pháo giặc, cởi giáp sắt ra và nhìn về kinh thành. Người đời gọi bạn là anh hùng, là thiên tài quân sự, là ‘Napoleon phương Đông’. Nhưng bạn – người từ tương lai – chỉ thầm nghĩ: "Nếu đây là định mệnh, ta xin sống nốt một đời này như một người xứng đáng với cái tên Quang Trung"."',
    song: 'Rewrite History – AI Remix',
    author: 'Nguyễn Quang Tiên',
    source: 'Nguồn: tiktok/@gn23',
    likes: 0,
    comments: 0,
    shares: 0,
  },
];

export default shortVideos;
